INSERT INTO ensemble (name, type, description) VALUES ('Led Zeppelin', 'quartet', 'Led Zeppelin (рус. Лед Зе́ппелин[2][3], МФА: [ˌlɛd ˈzɛpˌlɪn][4]) — британская рок-группа, образовавшаяся в сентябре 1968 года в Лондоне, и признанная одной из самых успешных, новаторских и влиятельных в современной истории[5]. Создав собственное звучание (для которого были характерны утяжелённый гитарный драйв, оглушающее звучание ритм-секции и пронзительный вокал), Led Zeppelin стали одной из ведущих групп хард-рока[6], сыграли основополагающую роль в становлении хеви-метала[1][7][8], свободно интерпретируя фолк- и блюз-классику и обогащая стиль элементами других музыкальных жанров (рокабилли, рэгги, соул, фанка, кантри)[9]. Остаётся одной из наиболее успешных групп в рок-музыке: общемировой тираж альбомов превышает 300 миллионов[10][11][12], 112 миллионов было продано в США (четвёртое место)[13]. Семь альбомов группы поднимались на вершину Billboard 200. Занимает первое место в списке VH1 «100 величайших артистов хард-рока»[14]. Журнал Rolling Stone признал коллектив «самой тяжёлой группой» и «лучшей группой 70-х»[15]. В 1995 году Led Zeppelin были введены в Зал славы рок-н-ролла, в 2005 году получили Грэмми за вклад на протяжении всей карьеры (Grammy Lifetime Achievement Award)[5], в мае 2006 года — Polar Music Prize[10].');

INSERT INTO musician (name, date, sex, description) VALUES ('Роберт Плант', '1948-08-20', true, 'Ро́берт Э́нтони Плант (англ. Robert Anthony Plant, 20 августа 1948, Уэст-Бромидж, Стаффордшир, Англия) — британский рок-вокалист, известный прежде всего участием в Led Zeppelin. После распада группы Плант начал успешную сольную карьеру, которая продолжается по сей день. Командор ордена Британской империи (CBE).');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Джимми Пейдж', '1944-01-09', true, 'Британский рок-музыкант, аранжировщик, композитор, музыкальный продюсер и гитарист-виртуоз, стоявший у истоков Led Zeppelin и до самого конца остававшийся музыкальным «мозгом» группы. До этого был известен как сессионный гитарист и участник The Yardbirds (c конца 1966 до 1968 года).');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Джон Пол Джонс', '1946-01-03', true, 'Джон Пол Джонс (англ. John Paul Jones; настоящее имя Джон Ри́чард Бо́лдуин (John Richard Baldwin); 3 января 1946 года, Сидкап (англ.)русск., Кент, Англия) — британский музыкант-мультиинструменталист, музыкальный продюсер, композитор, аранжировщик. Наиболее известен как басист и клавишник группы Led Zeppelin. В 2011 году признан одним из лучших бас-гитаристов всех времён согласно опросу, проведённому журналом Rolling Stone. Также занял 14-е место в списке 50 величайших басистов всех времён по версии редакции того же журнала.');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Джон Бонем', '1948-05-31', true, 'Джон Ге́нри Бо́нем (англ. John Henry Bonham; 31 мая 1948 года, Реддитч, Вустершир, Англия — 25 сентября 1980 года, Клюэр, Виндзор, Англия), также известный под прозвищем Бонзо (англ. Bonzo) — британский барабанщик-виртуоз, участник группы Led Zeppelin, за время игры в которой стал одним из величайших и влиятельнейших ударников в рок-музыке.Специалисты отмечали уникальную мощь его игры и чувство внутренней энергетики ритма. «Энциклопедия Британника» назвала Бонема «идеальным примером для всех барабанщиков хард-рока, которые пошли по его стопам»[5]. После смерти Бонема в возрасте 32 лет Led Zeppelin распались.В 2005 году британский журнал Classic Rock поставил Бонема на первое место в списке лучших рок-барабанщиков всех времён, также как и Rolling Stone в своём списке 100 величайших барабанщиков всех времён в 2016[6].');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO composition (name, date, ensemble_id, description) VALUES ('Stairway to Heaven', '1971-11-08', currval('ensemble_id_seq'), '«Stairway to Heaven» (с англ. — «Лестница на небеса») — песня британской рок-группы Led Zeppelin, выпущенная на альбоме Led Zeppelin IV. Композиция также вошла в концертный альбом The Song Remains the Same. Авторы песни — гитарист группы Джимми Пейдж и вокалист Роберт Плант. Эта песня стала одной из самых знаменитых композиций Led Zeppelin и рок-музыки вообще, а также самой часто проигрываемой композицией на FM-радиостанциях Америки. Между тем, она даже не была выпущена как сингл, а рекламное EP-издание для радиостанций вышло только в 1972 году. Как сингл песня вышла лишь в 2007 году и заняла в хит-параде Британии 37-е место. В песне можно выделить три отличные друг от друга части: акустическое мягкое вступление в стиле традиционных (даже средневековых) бардов, основная часть с более привычной, но всё ещё мягкой фактурой роковой баллады и заключительная "тяжёлая" часть, включающая гитарное соло.');
INSERT INTO composition (name, date, ensemble_id, description) VALUES ('Whole Lotta Love', '1969-11-07', currval('ensemble_id_seq'), '«Whole Lotta Love» — первая и самая известная песня второго альбома британской рок-группы Led Zeppelin, Led Zeppelin II. Визитной карточкой песни стал гитарный рифф, который в унисон играют Джимми Пейдж и Джон Пол Джонс, а также соло на электромагнитном инструменте терменвоксе (в сингловом варианте «Whole Lotta Love» это соло отсутствует).');
INSERT INTO composition (name, date, ensemble_id, description) VALUES ('Babe I’m Gonna Leave You', '1969-01-12', currval('ensemble_id_seq'), 'Babe I’m Gonna Leave You — вторая песня на первом альбоме британской рок-группы Led Zeppelin. Идея записать этот кавер пришла к Пейджу после того, как он услышал песню в исполнении Джоан Баэз. Существует версия 1968 года, записанная Пейджем со Стивом Уинвудом; она так и осталась невыпущенной.');
INSERT INTO composition (name, date, ensemble_id, description) VALUES ('Immigrant Song', '1970-11-05', currval('ensemble_id_seq'), 'Immigrant Song (с англ. — «Песня иммигранта») — песня британской хард-рок-группы Led Zeppelin, композиция Джимми Пейджа и Роберта Планта, первый трек альбома Led Zeppelin III.');




INSERT INTO ensemble (name, type, description) VALUES ('Deep Purple', 'quintet', 'Deep Purple (рус. Дип Пёрпл[1], МФА: [diːp ˈpɜː.pl̩]) — британская рок-группа, образованная в феврале 1968 года в Хартфорде, Англия, и считающаяся одной из самых заметных и влиятельных в хард-роке 1970-х годов. Музыкальные критики считают Deep Purple одними из основателей хард-рока и высоко оценивают их вклад в его развитие. Музыканты «классического» состава Deep Purple (в частности, гитарист Ричи Блэкмор, клавишник Джон Лорд, барабанщик Иэн Пейс) считаются инструменталистами-виртуозами. В мире продано более 100 миллионов копий их альбомов[2]. В 2016 году группа была введена в Зал славы рок-н-ролла.');

INSERT INTO musician (name, date, sex, description) VALUES ('Иэн Пэйс', '1948-06-29', true, 'И́эн (Ян) А́ндерсон Пейс (англ. Ian Anderson Paice; 29 июня 1948, Ноттингем, Англия) — британский барабанщик-виртуоз. Наиболее известен своим творчеством в составе Deep Purple. Единственный участник группы, входивший во все её составы и единственный остающийся в группе участник первого состава, при этом он никогда не был лидером группы. В списке «100 величайших барабанщиков всех времён» журнала Rolling Stone занял 21 место[1], а в списке 50 лучших барабанщиков рока по версии журнала Classic Rock — 8 место.');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Иэн Гиллан', '1945-08-19', true, 'И́эн (Ян) Ги́ллан (англ. Ian Gillan; 19 августа 1945, Хаунслоу, Мидлсекс, Великобритания) — британский рок-музыкант, вокалист и автор текстов песен. Наиболее известен как участник группы Deep Purple. Гиллан также исполнил партию Иисуса в оригинальной версии рок-оперы «Иисус Христос — суперзвезда» Э. Уэббера и Т. Райса и пел в течение года в Black Sabbath. В разное время участвовал в рок-группах Moonshiners, The Javelins, Wainwright''s Gentlemen (Sweet[источник не указан 1178 дней]), Episode Six, Ian Gillan Band, GILLAN. Записал альбом Born Again с группой Black Sabbath. Также участник супергруппы Whocares. Считается одним из мастеров грудного вокала в рок-музыке с диапазоном голоса от Е2 до С6.');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Роджер Гловер', '1945-11-30', true, 'Роджер Дэвид Гловер (англ. Roger David Glover; р. 30 ноября 1945, Брекон) — британский бас-гитарист, клавишник, автор песен и продюсер, участник группы Deep Purple.');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Стив Морс', '1954-07-28', true, 'Стивен Джей Морс (англ. Steven J. Morse; род. 28 июля 1954, Гамильтон, Огайо, США) — американский гитарист, автор песен, пилот. Несколько раз был признан лучшим гитаристом года по версии журнала «Guitar Player». Играет в группе «Deep Purple» c 1994 года, а также «Steve Morse Band». В 2009 году журналом Classic Rock включен в список величайших гитаристов всех времен.');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO musician (name, date, sex, description) VALUES ('Дон Эйри', '1948-06-21', true, 'Дон Э́йри (англ. Don Airey, полное имя — Дональд Смит Эйри, англ. Donald Smith Airey; род. 21 июня 1948, Сандерленд, Англия) — британский пианист, органист, композитор, аранжировщик. Получил известность, сотрудничая со многими известными группами в качестве сессионного музыканта. Наиболее известен как многолетний клавишник «Deep Purple». Старший брат гитариста Кита Эйри (англ. Keith Airey, «The Zombies»).');
INSERT INTO ensemble_musician(ensemble_id, musician_id) VALUES (currval('ensemble_id_seq'), currval('musician_id_seq'));
INSERT INTO musician_specialization(musician_id, specialization) VALUES (currval('musician_id_seq'), 'performer');

INSERT INTO composition (name, date, ensemble_id, description) VALUES ('Smoke on the Water', '1972-11-08', currval('ensemble_id_seq'), 'Smoke on the Water (с англ. — «Дым над водой») — песня рок-группы Deep Purple, записанная в декабре 1971 года и впервые выпущенная в альбоме Machine Head в марте 1972 года. В качестве сингла она вышла лишь в 1973 году; вторую сторону сингла занимала её концертная версия из альбома Made in Japan.');